export declare const auto: string
export declare const w1: string
export declare const w10: string
export declare const w100: string
export declare const w11: string
export declare const w12: string
export declare const w13: string
export declare const w14: string
export declare const w15: string
export declare const w16: string
export declare const w17: string
export declare const w18: string
export declare const w19: string
export declare const w2: string
export declare const w20: string
export declare const w21: string
export declare const w22: string
export declare const w23: string
export declare const w24: string
export declare const w25: string
export declare const w26: string
export declare const w27: string
export declare const w28: string
export declare const w29: string
export declare const w3: string
export declare const w30: string
export declare const w31: string
export declare const w32: string
export declare const w33: string
export declare const w34: string
export declare const w35: string
export declare const w36: string
export declare const w37: string
export declare const w38: string
export declare const w39: string
export declare const w4: string
export declare const w40: string
export declare const w41: string
export declare const w42: string
export declare const w43: string
export declare const w44: string
export declare const w45: string
export declare const w46: string
export declare const w47: string
export declare const w48: string
export declare const w49: string
export declare const w5: string
export declare const w50: string
export declare const w51: string
export declare const w52: string
export declare const w53: string
export declare const w54: string
export declare const w55: string
export declare const w56: string
export declare const w57: string
export declare const w58: string
export declare const w59: string
export declare const w6: string
export declare const w60: string
export declare const w61: string
export declare const w62: string
export declare const w63: string
export declare const w64: string
export declare const w65: string
export declare const w66: string
export declare const w67: string
export declare const w68: string
export declare const w69: string
export declare const w7: string
export declare const w70: string
export declare const w71: string
export declare const w72: string
export declare const w73: string
export declare const w74: string
export declare const w75: string
export declare const w76: string
export declare const w77: string
export declare const w78: string
export declare const w79: string
export declare const w8: string
export declare const w80: string
export declare const w81: string
export declare const w82: string
export declare const w83: string
export declare const w84: string
export declare const w85: string
export declare const w86: string
export declare const w87: string
export declare const w88: string
export declare const w89: string
export declare const w9: string
export declare const w90: string
export declare const w91: string
export declare const w92: string
export declare const w93: string
export declare const w94: string
export declare const w95: string
export declare const w96: string
export declare const w97: string
export declare const w98: string
export declare const w99: string
