import { type WorkoutData, workoutIds } from "../outputs/workout-data-schemas"

const { pullUpId, bridgeId, handstandId, legRaiseId, pushUpId, squatId } =
    workoutIds

export const mockPullUpWorkoutData: WorkoutData[] = [
    {
        key: "workout1",
        date: 1672531199000,
        reps: [10, 12, 15],
        level: 5,
        workoutId: pullUpId,
        comments: "Felt strong today!",
        user: "user1@example.com",
    },
    {
        key: "workout2",
        date: 1672617599000,
        reps: [8, 10, 12],
        level: 5,
        workoutId: pullUpId,
        comments: "Struggled with the last set.",
        user: "user1@example.com",
    },
    {
        key: "workout3",
        date: 1672703999000,
        reps: [20, 25, 30],
        level: 5,
        workoutId: pullUpId,
        comments: "Feeling stronger.",
        user: "user1@example.com",
    },
    {
        key: "workout4",
        date: 1672790399000,
        reps: [5, 7, 10],
        level: 5,
        workoutId: pullUpId,
        comments: "Struggled with the first set.",
        user: "user1@example.com",
    },
    {
        key: "workout5",
        date: 1672876799000,
        reps: [15, 18, 20],
        level: 5,
        workoutId: pullUpId,
        comments: "Felt strong today!",
        user: "user1@example.com",
    },
    {
        key: "workout6",
        date: 1672963199000,
        reps: [12, 14, 16],
        level: 5,
        workoutId: pullUpId,
        comments: "Grip was slipping.",
        user: "user1@example.com",
    },
]

export const mockLatestWorkoutData: WorkoutData[] = [
    {
        key: "workout1",
        date: 1672531199000,
        reps: [10, 12, 15],
        level: 5,
        workoutId: pullUpId,
        comments: "Felt strong today!",
        user: "user1@example.com",
    },
    {
        key: "workout2",
        date: 1672617599000,
        reps: [2, 1],
        level: 5,
        workoutId: handstandId,
        comments: "Struggled with the last set.",
        user: "user1@example.com",
    },
    {
        key: "workout3",
        date: 1672703999000,
        reps: [20, 25, 30],
        level: 5,
        workoutId: pushUpId,
        comments: "Feeling stronger",
        user: "user1@example.com",
    },
    {
        key: "workout4",
        date: 1672790399000,
        reps: [5, 7, 10],
        level: 5,
        workoutId: squatId,
        comments: "Struggled with the first set.",
        user: "user1@example.com",
    },
    {
        key: "workout5",
        date: 1672876799000,
        reps: [15, 18, 20],
        level: 5,
        workoutId: bridgeId,
        comments: "Felt strong today!",
        user: "user1@example.com",
    },
    {
        key: "workout6",
        date: 1672963199000,
        reps: [12, 14, 16],
        level: 5,
        workoutId: legRaiseId,
        comments: "Grip was slipping.",
        user: "user1@example.com",
    },
]
