name: CSS Quality Check
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install -D
      - name: Run stylelint
        run: pnpm lint:styles
  stylelint-check:
    name: Stylelint SCSS Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install -D
      - name: Run stylelint SCSS check
        run: pnpm stylelint-scss-check
