import { extendZodWithOpenApi } from "@anatine/zod-openapi";
import { WORKOUT_COLLECTIONS } from "@/modules/database/config/db";
import { z } from "zod";

extendZodWithOpenApi(z);

export const workoutCollectionsSchema = z.enum(WORKOUT_COLLECTIONS);

export const emailSchema = z.string().email();

const workoutSchema = z.object({
  key: z.string().openapi({
    title: "Unique ID",
    description: "A key generated by the firebase server",
    example: "1234567890",
  }),
  date: z
    .object({
      seconds: z.number(),
      nanoseconds: z.number(),
    })
    .openapi({
      title: "Date",
      description: "The date of the workout",
      example: {
        seconds: 1629997200,
        nanoseconds: 0,
      },
    }),
  reps: z.array(z.number()).openapi({
    title: "Reps",
    description: "An array with the number of reps, one for each set",
    example: [10, 10, 10],
  }),
  level: z.number().min(1).max(10).int().openapi({
    title: "Level",
    description: "The level of the workout from 1 to 10",
    example: 5,
  }),
  workout: workoutCollectionsSchema.openapi({
    title: "Workout",
    description: "The name of the workout",
    example: "pull-ups",
  }),
  comments: z.string().optional().openapi({
    title: "Comments",
    description: "An optional field with any comments about the workout",
    example: "I was tired today",
  }),
  user: emailSchema.openapi({
    title: "User",
    description: "The email of the user",
    example: "email@email.com",
  }),
});

export function workoutSchemaEmailLiteral(email: string) {
  return workoutSchema.extend({
    user: z.literal(email),
  });
}

export default workoutSchema;
