name: Check Project

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Generate SCSS types
              run: npm run generate-scss-types
            - name: Check types
              run: npm run check-types

            - name: Lint styles
              run: npm run lint:styles
            - name: Lint code
              run: npm run lint

            - name: Automated tests
              run: npm run test

            - name: Format code
              run: npm run format
