name: Check Types

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    check-types:
        uses: ./.github/workflows/common-steps.yml
        steps:
            - name: Generate SCSS types
              run: npm generate-scss-types
            - name: Check types
              run: npm check-types
