name: Lint

on: [push]

jobs:
    lint:
        uses: ./.github/workflows/common-steps.yml
        steps:
            - name: Lint styles
              run: npm lint:styles
            - name: Lint code
              run: npm lint
