name: Automated Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    tests:
        uses: ./.github/workflows/common-steps.yml
        steps:
            - name: Run Automated Tests
              run: npm test
